version: 2.1
workflows:
  version: 2
  main:
    jobs:
      
      - test-behat
      - test-phpunit:
          name: "Test with PHP 7.4"
          php_version: "7.4"
      - test-phpunit:
          name: "Test with PHP 8.0"
          php_version: "8.0"
      - test-phpunit:
          name: "Test with PHP 8.1"
          php_version: "8.1"
      - test-phpunit:
          name: "Test with PHP 8.2"
          php_version: "8.2"
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test-behat
jobs:
  test-behat:
    resource_class: small
    working_directory: ~/pantheon-systems/pantheon-advanced-page-cache
    parallelism: 1
    docker:
      - image: quay.io/pantheon-public/build-tools-ci:8.x-php8.2
    steps:
    - checkout
    - restore_cache:
        keys:
          - test-behat-dependencies-{{ checksum "composer.json" }}
    - run: composer install -n --prefer-dist
    - save_cache:
        key: test-behat-dependencies-{{ checksum "composer.json" }}
        paths:
          - vendor
    - run: echo $(openssl rand -hex 8) > /tmp/WORDPRESS_ADMIN_PASSWORD
    - run: |
        echo 'export TERMINUS_ENV=ci-$CIRCLE_BUILD_NUM' >> $BASH_ENV
        echo 'export TERMINUS_SITE=pantheon-advanced-page-cache' >> $BASH_ENV
        echo 'export SITE_ENV=pantheon-advanced-page-cache.ci-$CIRCLE_BUILD_NUM' >> $BASH_ENV
        echo 'export WORDPRESS_ADMIN_USERNAME=pantheon' >> $BASH_ENV
        echo 'export WORDPRESS_ADMIN_EMAIL=no-reply@getpantheon.com' >> $BASH_ENV
        echo 'export WORDPRESS_ADMIN_PASSWORD=$(cat /tmp/WORDPRESS_ADMIN_PASSWORD)' >> $BASH_ENV
        source $BASH_ENV
    - run: echo "StrictHostKeyChecking no" >> "$HOME/.ssh/config"
    - run: |
        if [ -z "$GITHUB_TOKEN" ]; then
          echo "GITHUB_TOKEN environment variables missing; assuming unauthenticated build"
          exit 0
        fi
        echo "Setting GitHub OAuth token with suppressed ouput"
        {
          composer config -g github-oauth.github.com $GITHUB_TOKEN
        } &> /dev/null
    - run: |
        if [ -z "$TERMINUS_TOKEN" ]; then
          echo "TERMINUS_TOKEN environment variables missing; assuming unauthenticated build"
          exit 0
        fi
        terminus auth:login --machine-token=$TERMINUS_TOKEN
    - run: ./bin/validate-fixture-version.sh
    - run: ./bin/behat-prepare.sh
    - run: ./bin/behat-test.sh --strict
    - run:
        command: ./bin/behat-cleanup.sh
        when: always
  test-phpunit:
    resource_class: small
    parameters:
      php_version:
        type: enum
        enum:
          - "7.4"
          - "8.2"
          - "8.1"
          - "8.0"
    working_directory: ~/pantheon-systems/pantheon-advanced-page-cache
    docker:
      - image: cimg/php:<< parameters.php_version >>
      - image: cimg/mariadb:10.4
    environment:
      - WP_TESTS_DIR: "/tmp/wordpress-tests-lib"
      - WP_CORE_DIR: "/tmp/wordpress/"
    steps:
      - checkout
      - restore_cache:
          keys:
            - test-phpunit-dependencies-{{ checksum "composer.json" }}
      - run: composer install -n --prefer-dist --ignore-platform-reqs
      - save_cache:
          key: test-phpunit-dependencies-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run:
          name: "Install Extras"
          command: |
            sudo apt-get update
            sudo apt-get install subversion
            sudo apt-get install mariadb-client
      - run:
          name: "Run Tests"
          command: |
            bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 latest
            composer phpunit
            WP_MULTISITE=1 composer phpunit
            rm -rf $WP_TESTS_DIR $WP_CORE_DIR
            bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 nightly true
            composer phpunit
