name: Composer and NPM Package Diff
on:
  pull_request:
    paths:
      - 'composer.lock' # Triggers when PHP dependencies change
      # - 'package-lock.json'  will be removed in #362
permissions:
  contents: write
  pull-requests: write
jobs:
  composer-diff:
    name: Composer Diff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate composer diff
        id: composer_diff
        uses: IonBazan/composer-diff-action@v1
      - uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ steps.composer_diff.outputs.composer_diff_exit_code != 0 }}
        with:
          header: composer-diff
          message: |
            <strong>Composer Changes</strong>

            ${{ steps.composer_diff.outputs.composer_diff }}
  # Is meant to be removed soon in #362
  # npm-diff:
  #   name: NPM Lockfile Diff
  #   runs-on: ubuntu-latest
  #   continue-on-error: true #if this job fails, won't block the PRs, just won't post the NPM diff comment.
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - name: Setup Node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '24'
  #         cache: 'npm'
  #     - name: Compile NPM packages
  #       run: npm ci
  #     - name: NPM Lockfile Changes (thin-edge)
  #       uses: thin-edge/action-npm-lockfile-changes@v2
  #       with:
  #         token: ${{ github.token }}
  #     - name: Dependency Review
  #       uses: actions/dependency-review-action@v4
